### PR TITLE
minimize sidebar in click outside 168

### PR DESCRIPTION
**Pull request by dancespiele**

### CODE REVIEW

**Review by SamusElderg — COMMENTED** [review]
Doesnt seem to work?

**Comment by SamusElderg** [comment]
> Doesnt seem to work?

Oh nevermind it only works on certain screen shapes/sizes; ill adapt it to suit the other sidebars 👍 
Thanks

**Review by SamusElderg — APPROVED** [review]
Done! Thanks!

**Comment by SamusElderg** [comment]
Closes #168

**Comment by dancespiele** [comment]
sorry I didn't check another screens, my bad

**Pull request merged**
