### PR TITLE
Change default theme#888

### PR DESCRIPTION
**Pull request by ArtyODonnell**
OnLoad checks users' system-theme settings. If it isn't dark mode, it will set the Dapp to dark mode, thus making it the default setting. Added some code for future in case we go towards the preferred theme approach by user's system setting and new theme colors. Checking it if the user changes it mid-use and changes the Dapp accordingly.

### CODE REVIEW

**Comment by SamusElderg** [comment]
@ArtyODonnell awesome thanks for this! I made a few changes, namely adding back in the localStorage preference (user's preferred setting as a priority over their device system setting) 

And a minor refactor some logic changes to be reused by each conditional check (a persistent toggle function and a non-persistent toggle function) which wasn't really required now but might be helpful when/if we extend this logic at a later stage

The most recent commit is not related to this theme provider, was just a change i wanted to bundle into this merge

Check thru and let me know what you think, then we can merge it in if we have no further changes

**Comment by ArtyODonnell** [comment]
@SamusElderg Looks good to me. Sorry you had to rewrite most of the code in the end. At least first step in contributing has been made i guess hahah.

**Comment by SamusElderg** [comment]
I didn't have to rewrite anything really, just refactored your stuff a lil bit and added some custom out of scope stuff! This work is very much appreciated!

**Comment by SamusElderg** [comment]
Closes #888

**Pull request merged**
